// src/components/staff/MemberPickList.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Search } from 'lucide-vue-next'
import { Input } from '@/components/ui/input'
import { Checkbox } from '@/components/ui/checkbox'

export interface PickableMember {
  id: string
  name: string
  /** Secondary line, e.g. "username · grade" for students or an email. */
  detail: string | null
}

/**
 * Searchable person picker used by the classroom-members dialog (multi-select,
 * students and teachers) and the assign dialog (single-select). Selection
 * state lives in the parent.
 */
const props = defineProps<{
  members: PickableMember[]
  /** Rows that cannot be picked (e.g. already in the classroom), with a badge. */
  disabledIds?: string[]
  disabledLabel?: string
  /** Single-select mode: picking a member replaces the selection. */
  single?: boolean
  searchPlaceholder: string
  emptyText: string
}>()

const selectedIds = defineModel<string[]>('selectedIds', { default: () => [] })

const search = ref('')

const disabledSet = computed(() => new Set(props.disabledIds ?? []))

const filteredMembers = computed(() => {
  const query = search.value.toLowerCase().trim()
  if (!query) return props.members
  return props.members.filter(
    (member) =>
      member.name.toLowerCase().includes(query) ||
      (member.detail?.toLowerCase().includes(query) ?? false),
  )
})

function toggle(id: string) {
  if (disabledSet.value.has(id)) return
  if (props.single) {
    selectedIds.value = selectedIds.value.includes(id) ? [] : [id]
    return
  }
  selectedIds.value = selectedIds.value.includes(id)
    ? selectedIds.value.filter((selected) => selected !== id)
    : [...selectedIds.value, id]
}
</script>

<template>
  <div class="space-y-2">
    <div class="relative">
      <Search class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
      <Input v-model="search" :placeholder="searchPlaceholder" class="pl-9" />
    </div>

    <div class="max-h-64 space-y-1 overflow-y-auto rounded-md border p-1">
      <p v-if="filteredMembers.length === 0" class="p-4 text-center text-sm text-muted-foreground">
        {{ emptyText }}
      </p>
      <button
        v-for="member in filteredMembers"
        :key="member.id"
        type="button"
        class="flex w-full items-center gap-3 rounded-md px-2 py-1.5 text-left text-sm transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-50"
        :disabled="disabledSet.has(member.id)"
        @click="toggle(member.id)"
      >
        <Checkbox
          class="pointer-events-none"
          :model-value="selectedIds.includes(member.id) || disabledSet.has(member.id)"
          :disabled="disabledSet.has(member.id)"
          tabindex="-1"
        />
        <span class="min-w-0 flex-1">
          <span class="block truncate font-medium">{{ member.name }}</span>
          <span v-if="member.detail" class="block truncate text-xs text-muted-foreground">
            {{ member.detail }}
          </span>
        </span>
        <span v-if="disabledSet.has(member.id)" class="shrink-0 text-xs text-muted-foreground">
          {{ disabledLabel }}
        </span>
      </button>
    </div>
  </div>
</template>

// src/lib/components/classrooms/member-pick-list.svelte
<script lang="ts" module>
	export interface PickableMember {
		id: string;
		name: string;
		/** Secondary line: "username · grade" for a student, an email for a teacher. */
		detail: string | null;
	}
</script>

<script lang="ts">
	import SearchIcon from '@lucide/svelte/icons/search';
	import { Badge } from '#lib/components/ui/badge/index.js';
	import { Checkbox } from '#lib/components/ui/checkbox/index.js';
	import * as Empty from '#lib/components/ui/empty/index.js';
	import * as Field from '#lib/components/ui/field/index.js';
	import * as InputGroup from '#lib/components/ui/input-group/index.js';
	import { ScrollArea } from '#lib/components/ui/scroll-area/index.js';

	/** A searchable list of people to tick. The selection belongs to the parent. */
	let {
		members,
		selectedIds = $bindable(),
		disabledIds,
		disabledLabel,
		searchPlaceholder,
		emptyText
	}: {
		members: PickableMember[];
		selectedIds: string[];
		/** People who cannot be picked, such as those already in the classroom. */
		disabledIds: string[];
		disabledLabel: string;
		searchPlaceholder: string;
		emptyText: string;
	} = $props();

	let search = $state('');

	const filtered = $derived.by(() => {
		const query = search.toLowerCase().trim();
		if (!query) return members;
		return members.filter(
			(member) =>
				member.name.toLowerCase().includes(query) || member.detail?.toLowerCase().includes(query)
		);
	});

	function toggle(id: string) {
		selectedIds = selectedIds.includes(id)
			? selectedIds.filter((selected) => selected !== id)
			: [...selectedIds, id];
	}
</script>

<div class="flex flex-col gap-2">
	<InputGroup.Root>
		<InputGroup.Addon>
			<SearchIcon />
		</InputGroup.Addon>
		<InputGroup.Input
			bind:value={search}
			type="search"
			aria-label={searchPlaceholder}
			placeholder={searchPlaceholder}
		/>
	</InputGroup.Root>

	<!-- An 18px box with an 8px inset. -->
	<ScrollArea class="max-h-64 rounded-2xl border">
		<Field.FieldGroup class="gap-1 p-2">
			{#each filtered as member (member.id)}
				{@const disabled = disabledIds.includes(member.id)}
				<Field.Field orientation="horizontal" data-disabled={disabled ? true : undefined}>
					<Checkbox
						id="pick-{member.id}"
						checked={disabled || selectedIds.includes(member.id)}
						onCheckedChange={() => toggle(member.id)}
						{disabled}
					/>
					<Field.FieldContent class="min-w-0 gap-0">
						<Field.FieldLabel for="pick-{member.id}" class="truncate"
							>{member.name}</Field.FieldLabel
						>
						{#if member.detail}
							<Field.FieldDescription class="truncate text-xs"
								>{member.detail}</Field.FieldDescription
							>
						{/if}
					</Field.FieldContent>
					{#if disabled}
						<Badge variant="secondary">{disabledLabel}</Badge>
					{/if}
				</Field.Field>
			{:else}
				<Empty.Root class="py-6">
					<Empty.Header>
						<Empty.Description>{emptyText}</Empty.Description>
					</Empty.Header>
				</Empty.Root>
			{/each}
		</Field.FieldGroup>
	</ScrollArea>
</div>
